name: Build and deploy GitHub Pages

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Setup wasm-pack
        run: curl --silent --show-error --fail https://rustwasm.github.io/wasm-pack/installer/init.sh | sh
      - name: Build
        run: wasm-pack build --target web --out-name package
      - name: Prepare deploy
        run: |
          rm --verbose pkg/.gitignore
          mkdir --verbose public
          cp --verbose index.html index.css public
          mv --verbose pkg public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
